server:
  port: 8082

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.219.105/XE
    username: Lee
    password: 1234
  devtools:
    restart:
      enabled: true

jwt:
  header: Authorization
  secret: member
  token-validity-in-seconds: 86400 # 60 * 60 * 24